#!/bin/sh
set -eu
. /usr/local/libexec/hookworm

# Install any pending updates first
if freebsd-update updatesready; then
    hookworm_eval freebsd-update install
fi

# Search for updates
hookworm_eval freebsd-update fetch
if freebsd-update updatesready; then
    # Install the updates
    hookworm_eval freebsd-update install
    if hookworm_ask "Reboot" "r"; then
        hookworm_eval reboot
    fi
fi
