#!/bin/sh
set -eu
. /usr/local/libexec/hookworm

# Update distro
hookworm_eval freebsd-update fetch
if freebsd-update updatesready; then
    hookworm_eval freebsd-update install
    hookworm_ask_reboot
fi
