#!/bin/sh
set -eu
. /usr/local/libexec/hookworm

# Update the ports-tree if it exists
if test -f "/usr/ports/README"; then
    hookworm_eval portsnap fetch update

    # Update the installed ports if portmaster is available
    if test -f "/usr/local/sbin/portmaster"; then
        ports=`pkg query --all '%n %R' | grep -E 'unknown-repository$' | awk '{ print $1 }'`
        hookworm_eval portmaster -G -x pkg --update-if-newer $ports
    fi
fi
